# Generated by Django 3.1.1 on 2020-09-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('full_text_search', '0002_auto_20200911_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverted_index',
            name='articles',
        ),
        migrations.AddField(
            model_name='inverted_index',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='full_text_search.article'),
        ),
        migrations.AlterField(
            model_name='inverted_index',
            name='position',
            field=models.IntegerField(),
        ),
    ]
