# Generated by Django 3.1.1 on 2020-09-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_text_search', '0003_auto_20200911_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inverted_index',
            options={'ordering': ['word', 'article', 'position']},
        ),
    ]
