# Generated by Django 3.1.1 on 2020-09-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_text_search', '0004_auto_20200912_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
