# Generated by Django 3.1.1 on 2020-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_text_search', '0005_auto_20200930_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stem_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField()),
                ('word', models.CharField(max_length=50)),
                ('occurrence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField()),
                ('word', models.CharField(max_length=50)),
                ('occurrence', models.IntegerField()),
            ],
        ),
    ]
