# Generated by Django 3.1.1 on 2020-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_text_search', '0006_stem_frequency_word_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='stem_whole_covid_token_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('word', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='whole_covid_token_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('word', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
